config/routes.rb
Wtf::Application.routes.draw do

  get "scanner/index"
  get "home/index"
  get '/auth/:provider/callback', to: 'providers#make'

  namespace :admin do
    get "panel/index"
    get "discounts/check", to: 'rules#check'
    post "panel/scanner", to: 'scanner#index'
    resources :rules, only: [:index, :create, :update, :destroy]
  end

  namespace :mobile do
    get "panel/index", to: 'home#index'
    get "panel/qrcode", to: 'home#qrcode'
  end

  devise_for :users

  root 'home#index'

  

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  acts_as_api
  belongs_to :user

  api_accessible :public do |template|
    template.add :uid
    template.add :provider
    template.add :token
    template.add :nickname
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/1
  def make
    auth_date = auth_hash
    @provider = Provider.new()
    @provider.provider = auth_date.provider
    @provider.uid = auth_date.uid
    @provider.token = auth_date.credentials.token
    @provider.secret = auth_date.credentials.secret
    @provider.nickname = auth_date.info.nickname
    @provider.user = current_user
    @provider.save
    redirect_to admin_panel_index_url
  end
  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render action: 'show', status: :created, location: @provider }
      else
        format.html { render action: 'new' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    def auth_hash
      request.env['omniauth.auth']
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:provider, :uid, :nickname, :token, :secret)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :secret %><br>
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>Uid</th>
      <th>Nickname</th>
      <th>Token</th>
      <th>Secret</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.provider %></td>
        <td><%= provider.uid %></td>
        <td><%= provider.nickname %></td>
        <td><%= provider.token %></td>
        <td><%= provider.secret %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @provider.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @provider.uid %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @provider.nickname %>
</p>

<p>
  <strong>Token:</strong>
  <%= @provider.token %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @provider.secret %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>