config/routes.rb
Wtf::Application.routes.draw do

  get "scanner/index"
  get "home/index"
  get '/auth/:provider/callback', to: 'providers#make'

  namespace :admin do
    get "panel/index"
    get "discounts/check", to: 'rules#check'
    post "panel/scanner", to: 'scanner#index'
    resources :rules, only: [:index, :create, :update, :destroy]
  end

  namespace :mobile do
    get "panel/index", to: 'home#index'
    get "panel/qrcode", to: 'home#qrcode'
  end

  devise_for :users

  root 'home#index'

  

end

app/models/rule.rb
class Rule < ActiveRecord::Base
  acts_as_api
  belongs_to :user

  api_accessible :public do |template|
    template.add :id
    template.add :api_services
    template.add :icon
    template.add :method
    template.add :what
    template.add :discount
  end
end

app/controllers/admin/rules_controller.rb
class Admin::RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
    render_for_api :public, :json => @rules
  end

  # GET /check
  def check
    #before we need to get the the rules
    @rules = Rule.where :user => current_user
    puts params
    if params[:customer_id]
      puts params
      customer = User.find(params[:customer_id])
      final_rule = []

      @rules.each do |rule|
        if rule.api_services == "twitter"
          #we need to configure the store client and the customer client
          #get the store provider
          customer_provider = customer.providers.find_by :provider => "twitter"
          puts customer_provider.uid
          store_provider = current_user.providers.where(:provider => "twitter").first
          store_client = Twitter::REST::Client.new do |config|
            config.consumer_key        = "N88tBKaeDFxxgl1eCqECzg"
            config.consumer_secret     = "DimoMYgcqZhH8LULk7dyNziTEQbTUjuyVBPjLtE"
            config.access_token        = store_provider.token
            config.access_token_secret = store_provider.secret
          end

          if rule.method == "mention"
            #check if the customer has mentioned the user
            mentions = store_client.mentions_timeline
            mentions.each do |mention|
              if mention.user.id == customer_provider.uid
                final_rule.push(rule)
                break
              end
            end
          elsif rule.method == "hashtag"
            hashtags = store_client.search(rule.what).collect
            hashtags.each do |hashtag|
              if hashtag.user.id == customer_provider.uid
                final_rule.push(rule)
                break
              end
            end
          elsif rule.method == "follow"
            followers = store_client.followers
            followers.each do |follower|
              if follower.id == customer_provider.uid
                final_rule.push(rule)
                break
              end
            end
          end
        end
      end
      puts final_rule
      render json: {result: true, code: final_rule}
    else
      render json: {result: false}
    end
  end
  # GET /rules/1
  # GET /rules/1.json
  def show
    render json: @rule
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new()
    @rule.what = rule_params[:what]
    @rule.discount = rule_params[:discount]
    @rule.icon = rule_params[:icon]
    @rule.method = rule_params[:method]
    @rule.api_services = rule_params[:api_services]
    @rule.user = current_user
    @rule.save()
    render json: @rule, status: :created
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    render json: {}

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find_by id: params[:id], user: current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.permit(:api_services, :icon, :method, :what, :discount, :user_id)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/admin/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :method %><br>
    <%= f.text_field :method %>
  </div>
  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/admin/rules/index.html.erb
<h1>Listing rules</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Icon</th>
      <th>Method</th>
      <th>Action</th>
      <th>Discount</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.type %></td>
        <td><%= rule.icon %></td>
        <td><%= rule.method %></td>
        <td><%= rule.action %></td>
        <td><%= rule.discount %></td>
        <td><%= rule.user %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/admin/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/admin/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @rule.type %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @rule.icon %>
</p>

<p>
  <strong>Method:</strong>
  <%= @rule.method %>
</p>

<p>
  <strong>Action:</strong>
  <%= @rule.action %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @rule.discount %>
</p>

<p>
  <strong>User:</strong>
  <%= @rule.user %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>