config/routes.rb
Wtf::Application.routes.draw do

  get "scanner/index"
  get "home/index"
  get '/auth/:provider/callback', to: 'providers#make'

  namespace :admin do
    get "panel/index"
    get "discounts/check", to: 'rules#check'
    post "panel/scanner", to: 'scanner#index'
    resources :rules, only: [:index, :create, :update, :destroy]
  end

  namespace :mobile do
    get "panel/index", to: 'home#index'
    get "panel/qrcode", to: 'home#qrcode'
  end

  devise_for :users

  root 'home#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap 101 Template</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap -->
  <%= stylesheet_link_tag "admin/panel", media: "all" %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/html5shiv.js"></script>
  <script src="../../assets/js/respond.min.js"></script>
  <![endif]-->
  <!--[if IE 7]>
  <link rel="stylesheet" href="assets/css/font-awesome-ie7.css">
  <![endif]-->
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WTFF...Admin</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#/">Home</a></li>
        <li><a href="#/rules">Rules</a></li>
        <li><a href="#/subscriptions">Subscriptions</a></li>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</div>
<div class="container" id="wtfContainer" ng-view>
</div>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<%= javascript_include_tag "admin/panel" %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../assets/ico/favicon.png">

  <title>Signin Template for Bootstrap</title>

  <%= stylesheet_link_tag "devise", media: "all" %>
  <%= csrf_meta_tags %>
</head>

<body>

<div class="container">
  <%= yield %>
</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>WTFF...ollowers</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<!-- NAVBAR
================================================== -->
<body>
<div class="navbar-wrapper">
  <div class="container">

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">WTFF...ollowers</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <% if user_signed_in? %>
                <li><%= link_to "Admin Panel", admin_panel_index_path %></li>
                <li class="pull-right"><%= link_to "Sign-Out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to "Sign-Up", new_user_registration_path %></li>
                <li class="pull-right"><%= link_to "Sign-In", new_user_session_path %></li>
            <% end %>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

<%= yield %>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../assets/ico/favicon.png">

  <title>Starter Template for Bootstrap</title>

  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag "mobile/home", media: "all" %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/html5shiv.js"></script>
  <script src="../../assets/js/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WTMM..obile</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#/">Home</a></li>
        <li><a href="#/social">Social</a></li>
        <li><a href="#/payments">Payments</a></li>
        <% if user_signed_in? %>
            <li class="pull-right"><%= link_to "Sign-Out", destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container" id="mobileContainer" ng-view></div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "mobile/home" %>
</body>
</html>